### ISSUE TITLE
paraphrasing_vae FileNotFoundError

### ISSUE THREAD

**Issue by c4n** [tomhosking/torchseq#11]
Hi Tom,
I'm trying to train paraphrase models using torchseq. Do you know where can I get './data/pretrained-vocabs/bert-base-uncased.embeddings.pt' ?

 FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained-vocabs/bert-base-uncased.embeddings.pt'

This is my json for the VAE model.
`{
    "name": "paraphrasing_vae",
    "tag": "examples",
    "task": "para",
    "env": {
        "cuda": true,
        "data_path": "./data",
        "gpu_device": 0

    },
    "json_dataset": {
        "path": "wikianswers-pp",
        "field_map": [
            {
                "type": "sample",
                "from": "qs",
                "to": "s1"
            },
            {
                "type": "sample",
                "from": "qs",
                "to": "s2"
            }
        ]
    },
    "training": {
        "dataset": "json",
        "use_preprocessed_data": false,
        "log_interval": 100,
        "optimizer": {
            "type": "adam",
            "lr_schedule": true,
            "lr": 0.01,
            "beta1": 0.9,
            "beta2": 0.98
            },
        "batch_size": 16,
        "optim_batch_size": 64,
        "clip_gradient": 5,
        "num_epochs": 120,
        "warmup_epochs": 30,
        "suppression_loss_weight": 0.0,
        "label_smoothing": 0.0,
        "early_stopping_lag": 0,
        "reset_metrics": true,
        "token_dropout": 0.2,
        "kl_warmup_steps": 10000
    },
    "eval": {
        "eval_batch_size": 16,
        "sampler": "beam",
        "max_out_len": 50
    },
    "beam_search": {
        "beam_width": 4,
        "beam_expansion": 2,
        "length_alpha": 1.0
    },
    "prepro": {
        "vocab_size": 30522,
        "sent_window": 0,
        "tok_window": 40,
        "concat_ctxt_ans": false,
        "bio_tagging": true,
        "tokenizer": "bert-base-uncased"
    },

    "dropout": 0.1,

    "raw_embedding_dim": 768,
    "embedding_dim": 768,
    "onehot_bio" : false,
    "bio_embedding_dim": 8,
    "freeze_embeddings": true,
    "freeze_projection": true,
    "directional_masks": true,

    "encdec": {
        "num_encoder_layers": 5,
        "num_decoder_layers": 5,
        "num_heads": 8,
        "dim_feedforward": 2048,
        "activation": "relu",
        "bert_encoder": false
    },
    "encoder": {
        "embedding_dim": 768
    },
    "decoder": {
        "embedding_dim": 768
    },
    "bottleneck": {
        "embedding_dim": 768,
        "variational": true,
        "num_similar_heads": 4
    }
}`

**Comment by tomhosking** [comment]
Hi, you can download those files from here:
https://github.com/tomhosking/separator/tree/main/data/pretrained-vocabs

I will add them to this repo as well.

**Comment by c4n** [comment]
thank you.
