### ISSUE TITLE
"torchseq/torchseq/models/samplers/teacher_force.py", line 16, in forward

### ISSUE THREAD

**Issue by c4n** [tomhosking/torchseq#12]
torchseq/torchseq/models/samplers/teacher_force.py", line 16, in forward

Hi, 
I'm trying to run paraphrase_vae. It doesn't seem to work.
the 'batch' dict does not have the  key  called 'target'.

 max_output_len = batch[tgt_field].size()[1]
*** KeyError: 'target'
 
I'm trying to debug it. These are the existing keys.

`(Pdb) batch.keys()
dict_keys(['s1_text', 's2_text', 's1', 's1_len', 's2', 's2_len', '_global_step'])`

**Comment by tomhosking** [comment]
Sorry about this - the examples are based on an old version of torchseq, I haven't quite got round to updating them. You can try changing your config so that the `field_map` looks like this:
```
"field_map": [
        {
            "type": "sample",
            "from": "qs",
            "to": "source"
        },
        {
            "type": "sample",
            "from": "qs",
            "to": "target"
        }
    ]
```

**Comment by c4n** [comment]
it works. Thank you.
