### ISSUE TITLE
Why put nn.Embedding on CPU?

### ISSUE THREAD

**Issue by yipliu** [tomhosking/torchseq#13]
Hi,

Really amazing work!

As We can see from [here](https://github.com/tomhosking/torchseq/blob/2fd7f8d41480a136a82bb8fb9dc4a1272e31c6ad/torchseq/agents/base.py#L41), you put it on CPU. Why did you do that?

Another question, where can I download [xxx.embeddings.pt](https://github.com/tomhosking/separator/blob/main/data/pretrained-vocabs/bert-base-uncased.embeddings.pt)

**Comment by tomhosking** [comment]
Yes, that's exactly how I generate those files :) It's mostly useful for GPU clusters without access to internet.
