### ISSUE TITLE
Pad IDs must be matched between input and output tokenizers

### ISSUE THREAD

**Issue by tomsherborne** [tomhosking/torchseq#3]
If you set the input tokenizer to a model such as "facebook/mbart-large-50-many-to-many-mmt" then the padding ID is 1. However, the rest of torchseq assumes pad ID is 0. This leads to a conflict in `json_dataloader.py` as the padding IDs can't be different:

https://github.com/tomhosking/torchseq/blob/99c9b286c7ffd48a4df466291ff329fcc25633af/torchseq/datasets/json_loader.py#L25

Suggestion (from you) is to add a field to each batch referencing the relevant Pad ID.

**Comment by tomhosking** [comment]
Better fix: change `JsonDataset.pad_and_order_sequences()` to accept a map from field->pad_id instead of a single pad_id

**Comment by tomhosking** [comment]
Fixed in 46c2e29707f7008f1a832e9b3fbe119077c5d2dd (finally!).
